import type { Metadata } from "next";
import { Geist, Geist_Mono, Anton } from "next/font/google";
import "./globals.css";
import NavButton from "./templates/NavButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Jonatas.dev | desenvolvedor web júnior",
  description: "Generated by create next app",
  icons: {
    icon: [{ url: '/icon.svg', type: 'image/svg+xml' }],
  }
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col">
        <header className="absolute flex w-full p-0.5 h-2.5 justify-between">
          <button className="text-ink font-bold flex gap-1 items-center cursor-pointer w-fit h-full">
            <img src="/icon.svg" alt="" className="h-full w-auto" />
            <p className="leading-none [text-box:trim-both_cap_alphabetic]">jonatas.dev</p>
          </button>
          <nav className="flex justify-end gap-0.5 w-fit">
            <NavButton value="Projetos" />
            <NavButton value="Experiências" />
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
